### ISSUE TITLE
Bad link on ezless.org

### ISSUE THREAD

**Issue by alafon** [stdclass/ezless#6]
Hi Phillip,

just to remind you that the links you used at http://ezless.org are not ok anymore (I don't know since when you've changed your github nickname/account).

Thanks for your good work.

Cheers.

**Comment by stdclass** [comment]
Hi Alafon,

thanks for the bug report. I changed my github account a few days ago and forgot to update the links on the website.
I'm gonna fix that immediately.

Regards,
Phillip
